name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        imgtag:
          - "golang:1.12-buster"
        goarch:
          - "amd64"

    container: "${{matrix.imgtag}}"
    env:
      GOPATH: "${{github.workspace}}/go"
      GOARCH: "${{matrix.goarch}}"
      SRCDIR: "go/src/github.com/open-fsm/vr"
      GO111MODULE: "on"

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{env.SRCDIR}}

      - name: test
        run: |
          cd $SRCDIR
          ./test.sh

  stats:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: "golang:1.12-buster"
    env:
      GOPATH: "${{github.workspace}}/go"
      SRCDIR: "go/src/github.com/open-fsm/vr"
      GO111MODULE: "on"

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{env.SRCDIR}}

      - name: install goveralls
        run: go get github.com/mattn/goveralls

      - name: submit coverage
        env:
          COVERALLS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd $SRCDIR
          ./coverage.sh -c